package com.ptagent.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_ID,
    ROUTE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    PATH_FORBIDDEN,
    REQUEST_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    ORIGIN_NOT_ALLOWED,
    INTERNAL_ERROR,

    AUTH_USER_NOT_FOUND,
    AUTH_DISABLED,
    AUTH_LOGIN_METHOD_INVALID,
    AUTH_IDENTITY_EXISTS,
    AUTH_VERIFICATION_CODE_INVALID,
    AUTH_VERIFICATION_CODE_EXPIRED,
    AUTH_RATE_LIMITED,
    AUTH_PROVIDER_UNAVAILABLE,
    AUTH_PHONE_EXISTS,
    AUTH_EMAIL_EXISTS,
    AUTH_REQUIRED,
    AUTH_SESSION_INVALID,
    ACCESS_DENIED,

    DEMAND_NOT_FOUND,
    DEMAND_INVALID_STATUS,
    APPLICATION_NOT_FOUND,
    APPLICATION_DUPLICATED,
    IMPORT_FILE_NOT_FOUND,
    IMPORT_INVALID_FILE,

    USER_NOT_FOUND,
    TEACHER_NOT_FOUND,
    TEACHER_PROFILE_NOT_FOUND,
    RESUME_NOT_FOUND,
    ORDER_NOT_FOUND,
    FEEDBACK_INVALID_SCORE
}
